-- migrate:up
ALTER TABLE Users ALTER created TYPE BIGINT;
ALTER TABLE UserAvatars ALTER created TYPE BIGINT;
ALTER TABLE UserEvents ALTER created TYPE BIGINT;
ALTER TABLE UserKeys ALTER created TYPE BIGINT;
ALTER TABLE UserKeys ALTER replaced TYPE BIGINT;
ALTER TABLE UserFollows ALTER created TYPE BIGINT;
ALTER TABLE UserTokens ALTER created TYPE BIGINT;
ALTER TABLE UserTokens ALTER expiration TYPE BIGINT;
ALTER TABLE Posts ALTER created TYPE BIGINT;
ALTER TABLE Posts ALTER published TYPE BIGINT;
ALTER TABLE Posts ALTER updated TYPE BIGINT;
ALTER TABLE PostComments ALTER created TYPE BIGINT;
ALTER TABLE PostComments ALTER updated TYPE BIGINT;
ALTER TABLE PostMediaFiles ALTER created TYPE BIGINT;
ALTER TABLE PostMedia ALTER added TYPE BIGINT;


-- migrate:down
ALTER TABLE Users ALTER created TYPE INTEGER;
ALTER TABLE UserAvatars ALTER created TYPE INTEGER;
ALTER TABLE UserEvents ALTER created TYPE INTEGER;
ALTER TABLE UserKeys ALTER created TYPE INTEGER;
ALTER TABLE UserKeys ALTER replaced TYPE INTEGER;
ALTER TABLE UserFollows ALTER created TYPE INTEGER;
ALTER TABLE UserTokens ALTER created TYPE INTEGER;
ALTER TABLE UserTokens ALTER expiration TYPE INTEGER;
ALTER TABLE Posts ALTER created TYPE INTEGER;
ALTER TABLE Posts ALTER published TYPE INTEGER;
ALTER TABLE Posts ALTER updated TYPE INTEGER;
ALTER TABLE PostComments ALTER created TYPE INTEGER;
ALTER TABLE PostComments ALTER updated TYPE INTEGER;
ALTER TABLE PostMediaFiles ALTER created TYPE INTEGER;
ALTER TABLE PostMedia ALTER added TYPE INTEGER;

