// Code generated by qtc from "actionCSS.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line web/template/email/partials/actionCSS.qtpl:2
package partials

//line web/template/email/partials/actionCSS.qtpl:2
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line web/template/email/partials/actionCSS.qtpl:2
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line web/template/email/partials/actionCSS.qtpl:2
func StreamActionCSS(qw422016 *qt422016.Writer) {
//line web/template/email/partials/actionCSS.qtpl:2
	qw422016.N().S(`<style>html {background: #1a1c1e;}.body {font: 600 17px \'Roboto\', Helvetica, Arial, sans-serif;color: #e6e6e6;background: #121212;padding-top: 16px;width: fit-content;margin: 16px auto;border-radius: 10px;}`)
//line web/template/email/partials/actionCSS.qtpl:18
	qw422016.N().S(`.t {font-size: 24px;text-align: center;color: #f2f2f2}`)
//line web/template/email/partials/actionCSS.qtpl:25
	qw422016.N().S(`.b {padding: unset;text-align: center;max-width: 400px;padding: 16px;margin: 0 auto}`)
//line web/template/email/partials/actionCSS.qtpl:34
	qw422016.N().S(`.l {margin: 10px 0}.l a {color: #fff;padding: 10px 16px;background-color: #640f2a;border-radius: 5px;cursor: pointer;text-decoration: none}.l a:hover {background-color: #470a1e}`)
//line web/template/email/partials/actionCSS.qtpl:52
	qw422016.N().S(`.s a {color: #e11d48;background-color: transparent;border-radius: 0;text-decoration: none;}.s a:hover {color: #f43f5e;}.py-2 {padding-top: 6px!important;}.pb-2, .py-2  {padding-bottom: 6px!important;}.s {font-size: 12px;}</style>`)
//line web/template/email/partials/actionCSS.qtpl:75
}

//line web/template/email/partials/actionCSS.qtpl:75
func WriteActionCSS(qq422016 qtio422016.Writer) {
//line web/template/email/partials/actionCSS.qtpl:75
	qw422016 := qt422016.AcquireWriter(qq422016)
//line web/template/email/partials/actionCSS.qtpl:75
	StreamActionCSS(qw422016)
//line web/template/email/partials/actionCSS.qtpl:75
	qt422016.ReleaseWriter(qw422016)
//line web/template/email/partials/actionCSS.qtpl:75
}

//line web/template/email/partials/actionCSS.qtpl:75
func ActionCSS() string {
//line web/template/email/partials/actionCSS.qtpl:75
	qb422016 := qt422016.AcquireByteBuffer()
//line web/template/email/partials/actionCSS.qtpl:75
	WriteActionCSS(qb422016)
//line web/template/email/partials/actionCSS.qtpl:75
	qs422016 := string(qb422016.B)
//line web/template/email/partials/actionCSS.qtpl:75
	qt422016.ReleaseByteBuffer(qb422016)
//line web/template/email/partials/actionCSS.qtpl:75
	return qs422016
//line web/template/email/partials/actionCSS.qtpl:75
}
