// Code generated by qtc from "email.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// Email template. All the other email templates implement this interface.

//line web/template/email.qtpl:3
package template

//line web/template/email.qtpl:3
import g "go-site/data/globals"

//line web/template/email.qtpl:4
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line web/template/email.qtpl:4
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line web/template/email.qtpl:4
type Email interface {
//line web/template/email.qtpl:4
	Header() string
//line web/template/email.qtpl:4
	StreamHeader(qw422016 *qt422016.Writer)
//line web/template/email.qtpl:4
	WriteHeader(qq422016 qtio422016.Writer)
//line web/template/email.qtpl:4
	Title() string
//line web/template/email.qtpl:4
	StreamTitle(qw422016 *qt422016.Writer)
//line web/template/email.qtpl:4
	WriteTitle(qq422016 qtio422016.Writer)
//line web/template/email.qtpl:4
	Body() string
//line web/template/email.qtpl:4
	StreamBody(qw422016 *qt422016.Writer)
//line web/template/email.qtpl:4
	WriteBody(qq422016 qtio422016.Writer)
//line web/template/email.qtpl:4
}

// Page prints a html email implementing Email interface.

//line web/template/email.qtpl:11
func StreamEmailTemplate(qw422016 *qt422016.Writer, p Email) {
//line web/template/email.qtpl:11
	qw422016.N().S(`<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><meta http-equiv="X-UA-Compatible" content="ie=edge">`)
//line web/template/email.qtpl:18
	p.StreamHeader(qw422016)
//line web/template/email.qtpl:18
	qw422016.N().S(`<title>`)
//line web/template/email.qtpl:19
	p.StreamTitle(qw422016)
//line web/template/email.qtpl:19
	qw422016.N().S(`</title></head><body>`)
//line web/template/email.qtpl:22
	p.StreamBody(qw422016)
//line web/template/email.qtpl:22
	qw422016.N().S(`</body></html>`)
//line web/template/email.qtpl:25
}

//line web/template/email.qtpl:25
func WriteEmailTemplate(qq422016 qtio422016.Writer, p Email) {
//line web/template/email.qtpl:25
	qw422016 := qt422016.AcquireWriter(qq422016)
//line web/template/email.qtpl:25
	StreamEmailTemplate(qw422016, p)
//line web/template/email.qtpl:25
	qt422016.ReleaseWriter(qw422016)
//line web/template/email.qtpl:25
}

//line web/template/email.qtpl:25
func EmailTemplate(p Email) string {
//line web/template/email.qtpl:25
	qb422016 := qt422016.AcquireByteBuffer()
//line web/template/email.qtpl:25
	WriteEmailTemplate(qb422016, p)
//line web/template/email.qtpl:25
	qs422016 := string(qb422016.B)
//line web/template/email.qtpl:25
	qt422016.ReleaseByteBuffer(qb422016)
//line web/template/email.qtpl:25
	return qs422016
//line web/template/email.qtpl:25
}

// Email implementation. Other emails may inherit from it if they needoverriding only certain Email methods

//line web/template/email.qtpl:32
type BaseEmail struct{}

//line web/template/email.qtpl:33
func (p *BaseEmail) StreamHeader(qw422016 *qt422016.Writer) {
//line web/template/email.qtpl:33
}

//line web/template/email.qtpl:33
func (p *BaseEmail) WriteHeader(qq422016 qtio422016.Writer) {
//line web/template/email.qtpl:33
	qw422016 := qt422016.AcquireWriter(qq422016)
//line web/template/email.qtpl:33
	p.StreamHeader(qw422016)
//line web/template/email.qtpl:33
	qt422016.ReleaseWriter(qw422016)
//line web/template/email.qtpl:33
}

//line web/template/email.qtpl:33
func (p *BaseEmail) Header() string {
//line web/template/email.qtpl:33
	qb422016 := qt422016.AcquireByteBuffer()
//line web/template/email.qtpl:33
	p.WriteHeader(qb422016)
//line web/template/email.qtpl:33
	qs422016 := string(qb422016.B)
//line web/template/email.qtpl:33
	qt422016.ReleaseByteBuffer(qb422016)
//line web/template/email.qtpl:33
	return qs422016
//line web/template/email.qtpl:33
}

//line web/template/email.qtpl:34
func (p *BaseEmail) StreamTitle(qw422016 *qt422016.Writer) {
//line web/template/email.qtpl:34
	qw422016.N().S(`Email`)
//line web/template/email.qtpl:34
}

//line web/template/email.qtpl:34
func (p *BaseEmail) WriteTitle(qq422016 qtio422016.Writer) {
//line web/template/email.qtpl:34
	qw422016 := qt422016.AcquireWriter(qq422016)
//line web/template/email.qtpl:34
	p.StreamTitle(qw422016)
//line web/template/email.qtpl:34
	qt422016.ReleaseWriter(qw422016)
//line web/template/email.qtpl:34
}

//line web/template/email.qtpl:34
func (p *BaseEmail) Title() string {
//line web/template/email.qtpl:34
	qb422016 := qt422016.AcquireByteBuffer()
//line web/template/email.qtpl:34
	p.WriteTitle(qb422016)
//line web/template/email.qtpl:34
	qs422016 := string(qb422016.B)
//line web/template/email.qtpl:34
	qt422016.ReleaseByteBuffer(qb422016)
//line web/template/email.qtpl:34
	return qs422016
//line web/template/email.qtpl:34
}

//line web/template/email.qtpl:35
func (p *BaseEmail) StreamBody(qw422016 *qt422016.Writer) {
//line web/template/email.qtpl:35
}

//line web/template/email.qtpl:35
func (p *BaseEmail) WriteBody(qq422016 qtio422016.Writer) {
//line web/template/email.qtpl:35
	qw422016 := qt422016.AcquireWriter(qq422016)
//line web/template/email.qtpl:35
	p.StreamBody(qw422016)
//line web/template/email.qtpl:35
	qt422016.ReleaseWriter(qw422016)
//line web/template/email.qtpl:35
}

//line web/template/email.qtpl:35
func (p *BaseEmail) Body() string {
//line web/template/email.qtpl:35
	qb422016 := qt422016.AcquireByteBuffer()
//line web/template/email.qtpl:35
	p.WriteBody(qb422016)
//line web/template/email.qtpl:35
	qs422016 := string(qb422016.B)
//line web/template/email.qtpl:35
	qt422016.ReleaseByteBuffer(qb422016)
//line web/template/email.qtpl:35
	return qs422016
//line web/template/email.qtpl:35
}
