package user

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *Perms) DecodeMsg(dc *msgp.Reader) (err error) {
	{
		var zb0001 int64
		zb0001, err = dc.ReadInt64()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = Perms(zb0001)
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z Perms) EncodeMsg(en *msgp.Writer) (err error) {
	err = en.WriteInt64(int64(z))
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z Perms) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendInt64(o, int64(z))
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Perms) UnmarshalMsg(bts []byte) (o []byte, err error) {
	{
		var zb0001 int64
		zb0001, bts, err = msgp.ReadInt64Bytes(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = Perms(zb0001)
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z Perms) Msgsize() (s int) {
	s = msgp.Int64Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *Session) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "loggedIn":
			z.LoggedIn, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "LoggedIn")
				return
			}
		case "userId":
			z.UserID, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "UserID")
				return
			}
		case "perms":
			{
				var zb0002 int64
				zb0002, err = dc.ReadInt64()
				if err != nil {
					err = msgp.WrapError(err, "Perms")
					return
				}
				z.Perms = Perms(zb0002)
			}
		case "privateKey":
			err = z.PrivateKey.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "PrivateKey")
				return
			}
		case "loginToken":
			z.LoginToken, err = dc.ReadBytes(z.LoginToken)
			if err != nil {
				err = msgp.WrapError(err, "LoginToken")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *Session) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 5
	// write "loggedIn"
	err = en.Append(0x85, 0xa8, 0x6c, 0x6f, 0x67, 0x67, 0x65, 0x64, 0x49, 0x6e)
	if err != nil {
		return
	}
	err = en.WriteBool(z.LoggedIn)
	if err != nil {
		err = msgp.WrapError(err, "LoggedIn")
		return
	}
	// write "userId"
	err = en.Append(0xa6, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.UserID)
	if err != nil {
		err = msgp.WrapError(err, "UserID")
		return
	}
	// write "perms"
	err = en.Append(0xa5, 0x70, 0x65, 0x72, 0x6d, 0x73)
	if err != nil {
		return
	}
	err = en.WriteInt64(int64(z.Perms))
	if err != nil {
		err = msgp.WrapError(err, "Perms")
		return
	}
	// write "privateKey"
	err = en.Append(0xaa, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79)
	if err != nil {
		return
	}
	err = z.PrivateKey.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "PrivateKey")
		return
	}
	// write "loginToken"
	err = en.Append(0xaa, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e)
	if err != nil {
		return
	}
	err = en.WriteBytes(z.LoginToken)
	if err != nil {
		err = msgp.WrapError(err, "LoginToken")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *Session) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 5
	// string "loggedIn"
	o = append(o, 0x85, 0xa8, 0x6c, 0x6f, 0x67, 0x67, 0x65, 0x64, 0x49, 0x6e)
	o = msgp.AppendBool(o, z.LoggedIn)
	// string "userId"
	o = append(o, 0xa6, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64)
	o = msgp.AppendInt64(o, z.UserID)
	// string "perms"
	o = append(o, 0xa5, 0x70, 0x65, 0x72, 0x6d, 0x73)
	o = msgp.AppendInt64(o, int64(z.Perms))
	// string "privateKey"
	o = append(o, 0xaa, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79)
	o, err = z.PrivateKey.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "PrivateKey")
		return
	}
	// string "loginToken"
	o = append(o, 0xaa, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e)
	o = msgp.AppendBytes(o, z.LoginToken)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Session) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "loggedIn":
			z.LoggedIn, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "LoggedIn")
				return
			}
		case "userId":
			z.UserID, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "UserID")
				return
			}
		case "perms":
			{
				var zb0002 int64
				zb0002, bts, err = msgp.ReadInt64Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Perms")
					return
				}
				z.Perms = Perms(zb0002)
			}
		case "privateKey":
			bts, err = z.PrivateKey.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "PrivateKey")
				return
			}
		case "loginToken":
			z.LoginToken, bts, err = msgp.ReadBytesBytes(bts, z.LoginToken)
			if err != nil {
				err = msgp.WrapError(err, "LoginToken")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Session) Msgsize() (s int) {
	s = 1 + 9 + msgp.BoolSize + 7 + msgp.Int64Size + 6 + msgp.Int64Size + 11 + z.PrivateKey.Msgsize() + 11 + msgp.BytesPrefixSize + len(z.LoginToken)
	return
}

// DecodeMsg implements msgp.Decodable
func (z *User) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "id":
			z.ID, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "ID")
				return
			}
		case "uniqueName":
			z.UniqueName, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "UniqueName")
				return
			}
		case "name":
			z.Name, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Name")
				return
			}
		case "email":
			z.Email, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Email")
				return
			}
		case "avatar":
			z.Avatar, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "Avatar")
				return
			}
		case "bio":
			z.Bio, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Bio")
				return
			}
		case "likes":
			z.Likes, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "Likes")
				return
			}
		case "permissions":
			{
				var zb0002 int64
				zb0002, err = dc.ReadInt64()
				if err != nil {
					err = msgp.WrapError(err, "Permissions")
					return
				}
				z.Permissions = Perms(zb0002)
			}
		case "created":
			z.Created, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "Created")
				return
			}
		case "publicKey":
			z.PublicKey, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "PublicKey")
				return
			}
		case "privateKeySalt":
			z.PrivateKeySalt, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "PrivateKeySalt")
				return
			}
		case "privateKey":
			z.PrivateKey, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "PrivateKey")
				return
			}
		case "backupKey":
			z.BackupKey, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "BackupKey")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *User) EncodeMsg(en *msgp.Writer) (err error) {
	// omitempty: check for empty values
	zb0001Len := uint32(13)
	var zb0001Mask uint16 /* 13 bits */
	if z.PublicKey == "" {
		zb0001Len--
		zb0001Mask |= 0x200
	}
	if z.PrivateKeySalt == "" {
		zb0001Len--
		zb0001Mask |= 0x400
	}
	if z.PrivateKey == "" {
		zb0001Len--
		zb0001Mask |= 0x800
	}
	if z.BackupKey == "" {
		zb0001Len--
		zb0001Mask |= 0x1000
	}
	// variable map header, size zb0001Len
	err = en.Append(0x80 | uint8(zb0001Len))
	if err != nil {
		return
	}
	if zb0001Len == 0 {
		return
	}
	// write "id"
	err = en.Append(0xa2, 0x69, 0x64)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.ID)
	if err != nil {
		err = msgp.WrapError(err, "ID")
		return
	}
	// write "uniqueName"
	err = en.Append(0xaa, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x4e, 0x61, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.UniqueName)
	if err != nil {
		err = msgp.WrapError(err, "UniqueName")
		return
	}
	// write "name"
	err = en.Append(0xa4, 0x6e, 0x61, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.Name)
	if err != nil {
		err = msgp.WrapError(err, "Name")
		return
	}
	// write "email"
	err = en.Append(0xa5, 0x65, 0x6d, 0x61, 0x69, 0x6c)
	if err != nil {
		return
	}
	err = en.WriteString(z.Email)
	if err != nil {
		err = msgp.WrapError(err, "Email")
		return
	}
	// write "avatar"
	err = en.Append(0xa6, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72)
	if err != nil {
		return
	}
	err = en.WriteBool(z.Avatar)
	if err != nil {
		err = msgp.WrapError(err, "Avatar")
		return
	}
	// write "bio"
	err = en.Append(0xa3, 0x62, 0x69, 0x6f)
	if err != nil {
		return
	}
	err = en.WriteString(z.Bio)
	if err != nil {
		err = msgp.WrapError(err, "Bio")
		return
	}
	// write "likes"
	err = en.Append(0xa5, 0x6c, 0x69, 0x6b, 0x65, 0x73)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.Likes)
	if err != nil {
		err = msgp.WrapError(err, "Likes")
		return
	}
	// write "permissions"
	err = en.Append(0xab, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73)
	if err != nil {
		return
	}
	err = en.WriteInt64(int64(z.Permissions))
	if err != nil {
		err = msgp.WrapError(err, "Permissions")
		return
	}
	// write "created"
	err = en.Append(0xa7, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.Created)
	if err != nil {
		err = msgp.WrapError(err, "Created")
		return
	}
	if (zb0001Mask & 0x200) == 0 { // if not empty
		// write "publicKey"
		err = en.Append(0xa9, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79)
		if err != nil {
			return
		}
		err = en.WriteString(z.PublicKey)
		if err != nil {
			err = msgp.WrapError(err, "PublicKey")
			return
		}
	}
	if (zb0001Mask & 0x400) == 0 { // if not empty
		// write "privateKeySalt"
		err = en.Append(0xae, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x53, 0x61, 0x6c, 0x74)
		if err != nil {
			return
		}
		err = en.WriteString(z.PrivateKeySalt)
		if err != nil {
			err = msgp.WrapError(err, "PrivateKeySalt")
			return
		}
	}
	if (zb0001Mask & 0x800) == 0 { // if not empty
		// write "privateKey"
		err = en.Append(0xaa, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79)
		if err != nil {
			return
		}
		err = en.WriteString(z.PrivateKey)
		if err != nil {
			err = msgp.WrapError(err, "PrivateKey")
			return
		}
	}
	if (zb0001Mask & 0x1000) == 0 { // if not empty
		// write "backupKey"
		err = en.Append(0xa9, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x4b, 0x65, 0x79)
		if err != nil {
			return
		}
		err = en.WriteString(z.BackupKey)
		if err != nil {
			err = msgp.WrapError(err, "BackupKey")
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *User) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// omitempty: check for empty values
	zb0001Len := uint32(13)
	var zb0001Mask uint16 /* 13 bits */
	if z.PublicKey == "" {
		zb0001Len--
		zb0001Mask |= 0x200
	}
	if z.PrivateKeySalt == "" {
		zb0001Len--
		zb0001Mask |= 0x400
	}
	if z.PrivateKey == "" {
		zb0001Len--
		zb0001Mask |= 0x800
	}
	if z.BackupKey == "" {
		zb0001Len--
		zb0001Mask |= 0x1000
	}
	// variable map header, size zb0001Len
	o = append(o, 0x80|uint8(zb0001Len))
	if zb0001Len == 0 {
		return
	}
	// string "id"
	o = append(o, 0xa2, 0x69, 0x64)
	o = msgp.AppendInt64(o, z.ID)
	// string "uniqueName"
	o = append(o, 0xaa, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x4e, 0x61, 0x6d, 0x65)
	o = msgp.AppendString(o, z.UniqueName)
	// string "name"
	o = append(o, 0xa4, 0x6e, 0x61, 0x6d, 0x65)
	o = msgp.AppendString(o, z.Name)
	// string "email"
	o = append(o, 0xa5, 0x65, 0x6d, 0x61, 0x69, 0x6c)
	o = msgp.AppendString(o, z.Email)
	// string "avatar"
	o = append(o, 0xa6, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72)
	o = msgp.AppendBool(o, z.Avatar)
	// string "bio"
	o = append(o, 0xa3, 0x62, 0x69, 0x6f)
	o = msgp.AppendString(o, z.Bio)
	// string "likes"
	o = append(o, 0xa5, 0x6c, 0x69, 0x6b, 0x65, 0x73)
	o = msgp.AppendInt64(o, z.Likes)
	// string "permissions"
	o = append(o, 0xab, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73)
	o = msgp.AppendInt64(o, int64(z.Permissions))
	// string "created"
	o = append(o, 0xa7, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64)
	o = msgp.AppendInt64(o, z.Created)
	if (zb0001Mask & 0x200) == 0 { // if not empty
		// string "publicKey"
		o = append(o, 0xa9, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79)
		o = msgp.AppendString(o, z.PublicKey)
	}
	if (zb0001Mask & 0x400) == 0 { // if not empty
		// string "privateKeySalt"
		o = append(o, 0xae, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x53, 0x61, 0x6c, 0x74)
		o = msgp.AppendString(o, z.PrivateKeySalt)
	}
	if (zb0001Mask & 0x800) == 0 { // if not empty
		// string "privateKey"
		o = append(o, 0xaa, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79)
		o = msgp.AppendString(o, z.PrivateKey)
	}
	if (zb0001Mask & 0x1000) == 0 { // if not empty
		// string "backupKey"
		o = append(o, 0xa9, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x4b, 0x65, 0x79)
		o = msgp.AppendString(o, z.BackupKey)
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *User) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "id":
			z.ID, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ID")
				return
			}
		case "uniqueName":
			z.UniqueName, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "UniqueName")
				return
			}
		case "name":
			z.Name, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Name")
				return
			}
		case "email":
			z.Email, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Email")
				return
			}
		case "avatar":
			z.Avatar, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Avatar")
				return
			}
		case "bio":
			z.Bio, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Bio")
				return
			}
		case "likes":
			z.Likes, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Likes")
				return
			}
		case "permissions":
			{
				var zb0002 int64
				zb0002, bts, err = msgp.ReadInt64Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Permissions")
					return
				}
				z.Permissions = Perms(zb0002)
			}
		case "created":
			z.Created, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Created")
				return
			}
		case "publicKey":
			z.PublicKey, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "PublicKey")
				return
			}
		case "privateKeySalt":
			z.PrivateKeySalt, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "PrivateKeySalt")
				return
			}
		case "privateKey":
			z.PrivateKey, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "PrivateKey")
				return
			}
		case "backupKey":
			z.BackupKey, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "BackupKey")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *User) Msgsize() (s int) {
	s = 1 + 3 + msgp.Int64Size + 11 + msgp.StringPrefixSize + len(z.UniqueName) + 5 + msgp.StringPrefixSize + len(z.Name) + 6 + msgp.StringPrefixSize + len(z.Email) + 7 + msgp.BoolSize + 4 + msgp.StringPrefixSize + len(z.Bio) + 6 + msgp.Int64Size + 12 + msgp.Int64Size + 8 + msgp.Int64Size + 10 + msgp.StringPrefixSize + len(z.PublicKey) + 15 + msgp.StringPrefixSize + len(z.PrivateKeySalt) + 11 + msgp.StringPrefixSize + len(z.PrivateKey) + 10 + msgp.StringPrefixSize + len(z.BackupKey)
	return
}
