// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type Post struct {
	Postid    int64
	Userid    int64
	Created   int64
	Published int64
	Updated   int64
	Content   string
}

type Postcomment struct {
	Postcommentid int64
	Postid        int64
	Userid        int64
	Parent        int64
	Created       int64
	Updated       int64
	Content       string
}

type Postcommentclosure struct {
	Parent int64
	Child  int64
	Depth  int64
}

type Postmediafile struct {
	Postmediafileid int64
	Created         int64
	Filetype        int32
	Width           int32
	Height          int32
	Hash            string
	Newhash         string
}

type Postmedium struct {
	Postmediaid     int64
	Postid          int64
	Added           int64
	Active          bool
	Alt             string
	Postmediafileid int64
}

type Session struct {
	Key        string
	Data       []byte
	Expiration int64
}

type User struct {
	Userid      int64
	Username    string
	Name        string
	Email       string
	Bio         string
	Type        int16
	Permissions int64
	Created     int64
}

type Useravatar struct {
	Useravatarid int64
	Userid       int64
	Active       bool
	Created      int64
	Filetype     int32
	Hash         string
}

type Userevent struct {
	Usereventid int32
	Userid      int64
	Eventtype   int16
	Created     int64
	Info        string
}

type Usereventkey struct {
	Usereventkeyid int64
	Usereventid    int32
	Userkeyid      int64
	Infokey        string
}

type Userfollow struct {
	Userfollowid int64
	Userid       int64
	Followuserid int64
	Accepted     bool
	Created      int64
}

type Userkey struct {
	Userkeyid       int64
	Userid          int64
	Created         int64
	Replaced        int64
	Authkeyhash     string
	Authkeysalt     string
	Publicarmored   string
	Privatearmored  string
	Recoverykeyhash string
	Recoveryarmored string
}

type Usertoken struct {
	Usertokenid int64
	Userid      int64
	Tokentype   int16
	Selector    string
	Token       string
	Created     int64
	Expiration  int64
}
